### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bertybuttface** [StanGirard/quiver#6]
What license is being used for this project?

Obsidian uses MIT License:

https://github.com/open-source-labs/obsidian/blob/master/LICENSE

**Comment by bertybuttface** [comment]
Hmm might be dual licensed actually: 

https://help.obsidian.md/Licenses+and+payment/Commercial+license

**Comment by StanGirard** [comment]
@bertybuttface added Apache2 ;)

**Comment by StanGirard** [comment]
Should be free enough 😅 I don't care about the money, i want the community to thrive
